# Generated by Django 5.2.4 on 2025-07-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_department_profile_enrollment_year_and_more'),
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
