# Generated by Django 5.2.4 on 2025-07-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
